In [0]:
import numpy

In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99,4])

In [25]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [27]:
a

array([ 2,  7,  1, 99,  4])

In [28]:
b

array([ 12,  17,  11, 199,  14])

In [29]:
a[0]

2

In [30]:
b[0]

12

In [31]:
a+b

array([ 14,  24,  12, 298,  18])

In [32]:
a+2

array([  4,   9,   3, 101,   6])

In [33]:
a+a

array([  4,  14,   2, 198,   8])

In [34]:
a*2

array([  4,  14,   2, 198,   8])

In [35]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
#method for declaring 2D array
x=np.array([[2,5,8], [3,6,1]])

In [37]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [38]:
x[0]

array([2, 5, 8])

In [39]:
#printing the elements of 2D array 
x[0][0]

2

In [40]:
x[0][2]

8

In [41]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x+7

In [43]:
y

array([[ 9, 12, 15],
       [10, 13,  8]])

In [44]:
y**2

array([[ 81, 144, 225],
       [100, 169,  64]])

In [45]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [46]:
x**3

array([[  8, 125, 512],
       [ 27, 216,   1]])

In [47]:
x[0]

array([2, 5, 8])

In [48]:
x[1]

array([3, 6, 1])

In [0]:
#method to print the coloumn of x array

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]        ])

In [51]:
z


array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [52]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [53]:
x.shape

(2, 3)

In [54]:
z.shape

(4, 2)

In [55]:
z[0]

array([2, 7])

In [56]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [57]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [59]:
x[0:][1]    ]

SyntaxError: ignored

In [60]:
z[0:2][1]

array([3, 8])

In [61]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [62]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [64]:
#method to print a coloumn in an 2D array
z[0:,0]

array([2, 3, 2, 9])

In [0]:
p=np.array([z[0][1],z[1][0]])

In [68]:
p

array([7, 3])

In [69]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [70]:
x[0:,1]

array([5, 6])

In [71]:
z[0:,1]

array([7, 8, 9, 4])

In [73]:
z[0:,0:1]

array([[2],
       [3],
       [2],
       [9]])

In [74]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [75]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [76]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [78]:
#printing random coloumns with rows
x[0:1,[0,2]]

array([[2, 8]])

In [79]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [80]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [81]:
z[[0,2]]

array([[2, 7],
       [2, 9]])

In [88]:
z[0:3]

array([[2, 7],
       [3, 8],
       [2, 9]])

In [89]:
z[[0,3]]

array([[2, 7],
       [9, 4]])

In [101]:
z[[0,3],1]

array([7, 4])

In [91]:
z[[0,3],[1]]

array([7, 4])

In [98]:
z[0: , 1]

array([7, 8, 9, 4])

In [99]:
z[0:,0:2]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [103]:
z[[0,2],1]

array([7, 9])

In [0]:
x1=x.reshape(3,2)

In [107]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])

In [108]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [119]:
#creating an  array with all the entries with zeroes
np.zeros((3,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [120]:
#creating an array with all the entries as 1
np.ones((3,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [121]:
#filling an array of size with a number
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [122]:
for i in dir(np):
    if 'zer' in i:
        print(i)

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like


In [123]:
[i for i in dir(np) if 'zer' in i]

['count_nonzero',
 'flatnonzero',
 'nonzero',
 'trim_zeros',
 'zeros',
 'zeros_like']